
stages:
  - build

# Python
build_python:
  except:
    - tags
  stage: build
  image: otel/build-protobuf
  variables:
    PROTOC: protoc-wrapper
  script:
    - ./scripts/python_build.sh

build_python_mstr:
  only:
    - tags
  stage: build
  image: otel/build-protobuf
  script:
    - pip install build twine
    - sed -i 's/VERSION/${CI_COMMIT_TAG}/' pyproject.toml
    - ./scripts/python_build.sh
    - python -m build build/python
    - python -m twine upload build/python/dist/*
