site_name: Deep Proto Docs
site_url: https://intergral.github.io/deep-proto/

theme:
  name: material

nav:
  - Common: common.md
  - Resource: resource.md
  - Poll: poll.md
  - Tracepoint: tracepoint.md

extra_css:
  - 'styles.css'