site_name: Deep Proto Docs
site_url: https://intergral.github.io/deep-proto/

repo_name: Deep Proto
repo_url: https://github.com/intergral/deep-proto

copyright: Intergral GmbH 2023

theme:
  logo: https://github.com/intergral/deep/blob/master/docs/docs/images/logo/icon.png?raw=true
  favicon: https://github.com/intergral/deep/blob/master/docs/docs/images/logo/icon.svg?raw=true
  name: material

nav:
  - Common: common.md
  - Resource: resource.md
  - Poll: poll.md
  - Tracepoint: tracepoint.md
  - Language Links:
      Java:
        Mvn Central: https://mvnrepository.com/artifact/com.intergral.deep/deep-proto
        Site: https://intergral.github.io/deep-proto/mvn/index.html
      Python:  https://pypi.org/project/deep-proto/
      GoLang: https://github.com/intergral/go-deep-proto

extra_css:
  - 'styles.css'