name: Build Proto

on:
  pull_request:
    branches: [ "master" ]

jobs:
  buildGo:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Generate Go Proto
        run: make gen-go

  buildPython:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.12'
      - name: Install deps
        run: pip install -r requirements.txt

      - name: Generate Python Proto
        run: make gen-python

  buildJava:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: 'maven'
      - name: Generate Java Proto
        run: make gen-java