name: Release Proto

on:
  release:
    types: [published]

env:
  VERSION: ${{ github.ref_name }}
  OSS_USERNAME: ${{ secrets.OSS_USERNAME }}
  OSS_PASSWORD: ${{ secrets.OSS_PASSWORD }}
  GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}

jobs:
  buildGo:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup key
        uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.GO_DEPLOY_KEY }}

      - name: Generate Go Proto
        run: make rel-go

  buildPython:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.x'

      - name: Generate Python Proto
        run: make rel-python

  buildJava:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: 'maven'
      - name: Generate Java Proto
        run: make rel-java