name: Release Proto

on:
  release:
    types: [published]

env:
  VERSION: $GITHUB_REF
  OSS_USERNAME: ${{ secrets.OSS_USERNAME }}
  OSS_PASSWORD: ${{ secrets.OSS_PASSWORD }}
  GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Generate Go Proto
        run: make rel-go

      - name: Generate Python Proto
        run: make rel-python

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: 'maven'
      - name: Generate Java Proto
        run: make rel-java